# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  CHIP8Interpreter_config = release

else ifeq ($(config),debug)
  CHIP8Interpreter_config = debug

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := CHIP8Interpreter

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

CHIP8Interpreter:
ifneq (,$(CHIP8Interpreter_config))
	@echo "==== Building CHIP8Interpreter ($(CHIP8Interpreter_config)) ===="
	@${MAKE} --no-print-directory -C CHIP8Interpreter -f Makefile config=$(CHIP8Interpreter_config)
endif

clean:
	@${MAKE} --no-print-directory -C CHIP8Interpreter -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   CHIP8Interpreter"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"